version: "3.1"

services:
  pingdirectory:
    image: pingidentity/pingdirectory
    environment:
      - SERVER_PROFILE_URL=https://github.com/arnaudlacour/server-profile-pingdirectory-replicated-pair.git
    networks:
      - pingnet
  pingdataconsole:
    image: pingidentity/pingdataconsole
    ports:
      - 8080:8080
    networks: 
      - pingnet
                    
networks:
    pingnet: