version: "3.1"
#
# This compose file offers mirrors the configuration provided in
# 00-docker-standalone/01-pingdirectory "Simplest way"
# 
#        

networks:
    pingnet:

services:
  pingdirectory:
    image: pingidentity/pingdirectory
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/server-profile-pingdirectory-basic.git
    deploy:
      replicas: 1
    ports:
      - 4636:636
      - 4443:443
    networks:
      - pingnet
    volumes:
      - /tmp/Swarm/basic1/pingdirectory:/opt/out
