kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../01-standalone

# The only difference in standalone deployments vs "fullstack" (integrated) is the product configurations. 
# here we replace standalone server-profiles ("getting-started") with "baseline" for each product
patchesStrategicMerge:
- |-
  apiVersion: v1
  data:
    env_vars: |-
      SERVER_PROFILE_URL="https://www.github.com/pingidentity/pingidentity-server-profiles.git"
      SERVER_PROFILE_PATH="baseline/pingaccess"
  kind: ConfigMap
  metadata:
    name: pingaccess-environment-variables
- |-
  apiVersion: v1
  data:
    env_vars: |-
      SERVER_PROFILE_URL="https://www.github.com/pingidentity/pingidentity-server-profiles.git"
      SERVER_PROFILE_PATH="baseline/pingdatagovernance"
  kind: ConfigMap
  metadata:
    name: pingdatagovernance-environment-variables
- |-
  apiVersion: v1
  data:
    env_vars: |-
      SERVER_PROFILE_URL="https://www.github.com/pingidentity/pingidentity-server-profiles.git"
      SERVER_PROFILE_PATH="baseline/pingdirectory"
  kind: ConfigMap
  metadata:
    name: pingdirectory-environment-variables
- |-
  apiVersion: v1
  data:
    env_vars: |-
      SERVER_PROFILE_URL="https://www.github.com/pingidentity/pingidentity-server-profiles.git"
      SERVER_PROFILE_PATH="baseline/pingfederate"
  kind: ConfigMap
  metadata:
    name: pingfederate-environment-variables
