kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../01-standalone/pingdataconsole
- ../01-standalone/pingdirectory
- storage.yaml

patchesStrategicMerge:
- |-
  apiVersion: v1
  data:
    env_vars: |-
      SERVER_PROFILE_URL="https://www.github.com/pingidentity/pingidentity-server-profiles.git"
      SERVER_PROFILE_PATH="baseline/pingdirectory"
      ORCHESTRATION_TYPE="KUBERNETES"
      K8S_STATEFUL_SET_NAME="pingdirectory"
      K8S_STATEFUL_SET_SERVICE_NAME="pingdirectory"
      MAKELDIF_USERS="1000"
      TAIL_LOG_FILES=""
  kind: ConfigMap
  metadata:
    name: pingdirectory-environment-variables

patches:
- target:
    kind: StatefulSet
    name: pingdirectory
  patch: |-
    - op: add
      path: /spec/replicas
      value: 2
- target:
    kind: StatefulSet
    name: pingdirectory
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts
      value: [{"name":"out-dir","mountPath":"/opt/out"}]
- target:
    kind: StatefulSet
    name: pingdirectory
  patch: |-
    - op: add
      path: /spec/volumeClaimTemplates
      value: [{"metadata":{"name":"out-dir"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"5Gi"}},"storageClassName":"pingdirectory-gp2"}}]
- target:
    kind: StatefulSet
    name: pingdirectory
  patch: |-
    - op: add
      path: /spec/template/spec/volumes
      value: [{"name":"out-dir","persistentVolumeClaim":{"claimName":"out-dir"}}]
