apiVersion: v1
kind: Service
metadata:
  name: pingaccessengine
  labels:
    app: pingaccessengine
spec:
  ports:
    - port: 443
      name: pa-engine
      targetPort: 3000
  selector:
    app: pingaccessengine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingaccessengine
  labels:
    app: pingaccessengine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingaccessengine
  template:
    metadata:
      name: pingaccessengine
      labels:
        app: pingaccessengine
    spec:
      containers:
      - name: pingaccessengine
        image: pingidentity/pingaccess:5.2.3-edge
        ports:        
        - containerPort: 3000
        env:
        - name: SERVER_PROFILE_URL
          value: "https://www.github.com/pingidentity/pingidentity-server-profiles.git"
        - name: SERVER_PROFILE_PATH
          value: "pa-clustering/pingaccess"
        - name: OPERATIONAL_MODE
          value: "CLUSTERED_ENGINE"
        - name: PA_CONSOLE_HOST
          value: pingaccess
        envFrom:
        - secretRef:
            name: devops-secret