version: "3.1"

services:
  pingfederate:
    image: pingidentity/pingfederate
    command: wait-for pingdirectory:389 -t 300 -- entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/server-profile-pingidentity-baseline.git
      - SERVER_PROFILE_PATH=pingfederate
    ports:
      - 9031:9031
      - 9999:9999
    networks:
      - pingnet

  pingdirectory:
    image: pingidentity/pingdirectory
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/server-profile-pingidentity-baseline.git
      - SERVER_PROFILE_PATH=pingdirectory
      # - VERBOSE=true
    ports:
      - 1636:636
      - 1443:443
    networks:
      - pingnet
                    
networks:
    pingnet:
