kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- pingdirectory.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: pingdirectory-environment-variables
  files:
    - env_vars