kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- pingaccess.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: pingaccess-environment-variables
  envs:
    - env_vars
