kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../

patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: Deployment
  metadata:
    name: pingaccess
  spec:
    template:
      spec:
        containers:
        - name: pingaccess
          image: nginx:latest