apiVersion: v1
kind: Service
metadata:
  name: pingaccess
  labels:
    app: pingaccess
spec:
  ports:
    - port: 9000
      name: pa-admin
    - port: 9090
      name: pa-cluster
  selector:
    app: pingaccess
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingaccess
  labels:
    app: pingaccess
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingaccess
  template:
    metadata:
      name: pingaccess
      labels:
        app: pingaccess
    spec:
      containers:
      - name: pingaccess
        image: pingidentity/pingaccess:5.2.3-edge
        ports:
        - containerPort: 9000
        - containerPort: 9090
        env:
        - name: SERVER_PROFILE_URL
          value: "https://www.github.com/pingidentity/pingidentity-server-profiles.git"
        - name: SERVER_PROFILE_PATH
          value: "pa-clustering/pingaccess"
        - name: OPERATIONAL_MODE
          value: "CLUSTERED_CONSOLE"
        - name: PA_CONSOLE_HOST
          value: pingaccess
        envFrom:
        - secretRef:
            name: devops-secret