apiVersion: v1
kind: Service
metadata:
  name: pingfederate-engine
  labels:
    role: pingfederate
    tier: engine

spec:
  ports:
    - port: 443
      name: pingfederate-engine
      targetPort: 9031
  selector:
    role: pingfederate
    tier: engine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingfederate-engine
  labels:
    role: pingfederate
    tier: engine
spec:
  replicas: 2
  selector:
    matchLabels:
      role: pingfederate
      tier: engine
  template:
    metadata:
      name: pingfederate-engine
      labels:
        role: pingfederate
        tier: engine
    spec:
      containers:
      - name: pingfederate-engine
        image: pingidentity/pingfederate:edge
        imagePullPolicy: Always
        ports:        
        - containerPort: 9031
        envFrom:
        - configMapRef:
            name: pingfederate-engine-environment-variables
        - secretRef:
            name: devops-secret
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /pf/heartbeat.ping
            port: 9031
            scheme: HTTPS
          initialDelaySeconds: 150
          periodSeconds: 1
        readinessProbe:
          httpGet:
            path: /pf/heartbeat.ping
            port: 9031
            scheme: HTTPS
          periodSeconds: 10
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh","-c","sleep 20"]
        resources:
          limits:
            cpu: "1"
            memory: 1.5Gi
          requests:
            cpu: "1"
            memory: 1.5Gi
      initContainers:
      - name: init
        image: curlimages/curl:latest
        command: ['sh', '-c', 'until curl --connect-timeout 1 --silent -k https://pingfederate:9999/pingfederate/app ; do echo waiting for admin ; sleep 2 ; done']